# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

test_results_dir: &test_results_dir /tmp/test_results

jobs:
  run-tests:
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.16.2
        environment:
          TEST_RESULTS_DIR: *test_results_dir

    working_directory: /go/src/github.com/hashicorp/go-tfe

    steps:
      - checkout

      - run:
          name: Make test results directory
          command: mkdir -p $TEST_RESULTS_DIR

      - run:
          name: Run tests
          command: |
              export GO111MODULE=on
              gotestsum --format short-verbose --junitfile \
              $TEST_RESULTS_DIR/tests.xml -- -timeout=40m -tags=integration
          no_output_timeout: 1800

      - store_test_results:
          path: *test_results_dir


workflows:
  version: 2
  my-workflow:
    jobs:
      - run-tests:
          context: core-team-access
